name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  RunTests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pyver: [ '3.9', '3.10' ]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.pyver }}
          cache: 'pip' # caching pip dependencies
      - run: pip install -r requirements.txt

      - name: run tests
        working-directory: ${{github.workspace}}
        run: python3 -m pytest